### ISSUE TITLE
Spatial extension gives error. 

### ISSUE THREAD

**Issue by alperdincer** [tobilg/serverless-duckdb#2]
I'm trying to run DuckDB with Spatial Extension but when I try to run the following query, I got time out error:

await query(`LOAD '/opt/nodejs/node_modules/duckdb/extensions/spatial.duckdb_extension';`);

I've added the following layer to Lambda :

arn:aws:lambda:us-east-1:041475135427:layer:duckdb-nodejs-spatial-x86:2 

I don't have any problems with the following queries : 

await query(`SET home_directory='/tmp';`);
await query(`LOAD httpfs;`);
await query(`PRAGMA version;`);

Anything else to check?

**Comment by tobilg** [comment]
Will check, but I‘m pretty sure it worked for me. In the meantime, try loading it dynamically as outlined in https://extensions.quacking.cloud eventually

**Comment by tobilg** [comment]
Ah, another thing, have you done an

INSTALL spatial;

before the load statement?

**Comment by tobilg** [comment]
Hm, I just tried it with my deployment, and it seems to work, as I see a result when running `SELECT * FROM st_drivers();`. Did you enable the layer at https://github.com/tobilg/serverless-duckdb/blob/main/serverless.yml#L78 and then include the load statement in https://github.com/tobilg/serverless-duckdb/blob/main/src/functions/query.js#L71?

**Comment by tobilg** [comment]
Any updates @alperdincer?

**Comment by alperdincer** [comment]
Sorry for late update:

I didn't use serverless.yml, I've added layer manually and run the load statement, but still got timeout even I set time-out to 15 seconds. 

RunTime : NodeJS 18.x and Architecture : x86_64 

Loaded Layer :  arn:aws:lambda:us-east-1:041475135427:layer:duckdb-nodejs-spatial-x86:2

**Comment by tobilg** [comment]
I‘m afaik that without knowing your Lambda handler code I will not be able to assist any further then.

**Comment by alperdincer** [comment]
There isn't much on Lambda Handler, which is as follows:

`import DuckDB from 'duckdb';

export const handler = async (event) => {
  
  // Instantiate DuckDB
  const duckDB = new DuckDB.Database(':memory:');
  
  // Create connection
  const connection = duckDB.connect();
  
  // Promisify query method
  const query = (query) => {
    return new Promise((resolve, reject) => {
      connection.all(query, (err, res) => {
        if (err) reject(err);
        resolve(res);
      })
    })
  }
  
  // Will show DuckDB version
  await query(`SET home_directory='/tmp';`);
  //await query(`LOAD httpfs;`);
  await query(`LOAD '/opt/nodejs/node_modules/duckdb/extensions/spatial.duckdb_extension';`);
  //await query(`SET custom_extension_repository = 'http://extensions.quacking.cloud';`);
  //await query(`INSTALL spatial;`);
  //await query(`LOAD spatial;`);
  
  var res1 = await query(`PRAGMA version;`);
  //var res1 = await query(`LOAD '/opt/nodejs/node_modules/duckdb/extensions/spatial.duckdb_extension';`);
  var res2 = await query(`SELECT * FROM st_drivers();`);
  
  console.log(res1);
  console.log(res2);
  console.log("------------------------------------------------------");
  
  
  const response = {
    statusCode: 200,
    body: JSON.stringify('Hello from Lambda!'),
  };
  return response;
};
`

Thanks for your help.

**Comment by tobilg** [comment]
This works now if you use the default x86 version of the Lambda layer. Also see:
* https://extensions.quacking.cloud/
* https://github.com/tobilg/serverless-duckdb/blob/main/src/functions/query.ts#L67-L71
